#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("ExploreOTCAndroid.Resource", IsApplication=true)]

namespace ExploreOTCAndroid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::PCLCrypto.Resource.String.ApplicationName = global::ExploreOTCAndroid.Resource.String.ApplicationName;
			global::PCLCrypto.Resource.String.Hello = global::ExploreOTCAndroid.Resource.String.Hello;
			global::PCLStorage.Resource.String.ApplicationName = global::ExploreOTCAndroid.Resource.String.ApplicationName;
			global::PCLStorage.Resource.String.Hello = global::ExploreOTCAndroid.Resource.String.Hello;
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7f080000
			public const int school_array = 2131230720;
			
			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010003
			public const int buttonSize = 2130771971;
			
			// aapt resource value: 0x7f010002
			public const int circleCrop = 2130771970;
			
			// aapt resource value: 0x7f010004
			public const int colorScheme = 2130771972;
			
			// aapt resource value: 0x7f010001
			public const int imageAspectRatio = 2130771969;
			
			// aapt resource value: 0x7f010000
			public const int imageAspectRatioAdjust = 2130771968;
			
			// aapt resource value: 0x7f010005
			public const int scopeUris = 2130771973;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f050008
			public const int common_google_signin_btn_text_dark = 2131034120;
			
			// aapt resource value: 0x7f050000
			public const int common_google_signin_btn_text_dark_default = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int common_google_signin_btn_text_dark_disabled = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int common_google_signin_btn_text_dark_focused = 2131034114;
			
			// aapt resource value: 0x7f050003
			public const int common_google_signin_btn_text_dark_pressed = 2131034115;
			
			// aapt resource value: 0x7f050009
			public const int common_google_signin_btn_text_light = 2131034121;
			
			// aapt resource value: 0x7f050004
			public const int common_google_signin_btn_text_light_default = 2131034116;
			
			// aapt resource value: 0x7f050005
			public const int common_google_signin_btn_text_light_disabled = 2131034117;
			
			// aapt resource value: 0x7f050006
			public const int common_google_signin_btn_text_light_focused = 2131034118;
			
			// aapt resource value: 0x7f050007
			public const int common_google_signin_btn_text_light_pressed = 2131034119;
			
			// aapt resource value: 0x7f05000a
			public const int common_google_signin_btn_tint = 2131034122;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int banner = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int BLUE1 = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int BLUEBACK = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int common_full_open_on_phone = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int common_google_signin_btn_icon_dark = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int common_google_signin_btn_icon_dark_focused = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int common_google_signin_btn_icon_dark_normal = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int common_google_signin_btn_icon_dark_normal_background = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int common_google_signin_btn_icon_disabled = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int common_google_signin_btn_icon_light = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int common_google_signin_btn_icon_light_focused = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int common_google_signin_btn_icon_light_normal = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int common_google_signin_btn_icon_light_normal_background = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int common_google_signin_btn_text_dark = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int common_google_signin_btn_text_dark_focused = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int common_google_signin_btn_text_dark_normal = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int common_google_signin_btn_text_dark_normal_background = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int common_google_signin_btn_text_disabled = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int common_google_signin_btn_text_light = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int common_google_signin_btn_text_light_focused = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int common_google_signin_btn_text_light_normal = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int common_google_signin_btn_text_light_normal_background = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int download = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int events = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int googleg_disabled_color_18 = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int googleg_standard_color_18 = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int history = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public const int Icon = 2130837531;
			
			// aapt resource value: 0x7f02001c
			public const int logo = 2130837532;
			
			// aapt resource value: 0x7f02001d
			public const int map = 2130837533;
			
			// aapt resource value: 0x7f02001e
			public const int mapPlaceholder = 2130837534;
			
			// aapt resource value: 0x7f02001f
			public const int programs = 2130837535;
			
			// aapt resource value: 0x7f020020
			public const int QR_code = 2130837536;
			
			// aapt resource value: 0x7f020021
			public const int qrCode = 2130837537;
			
			// aapt resource value: 0x7f020022
			public const int qrimage = 2130837538;
			
			// aapt resource value: 0x7f020023
			public const int search = 2130837539;
			
			// aapt resource value: 0x7f020024
			public const int survey = 2130837540;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f0a0025
			public const int SubmitButton = 2131361829;
			
			// aapt resource value: 0x7f0a0000
			public const int adjust_height = 2131361792;
			
			// aapt resource value: 0x7f0a0001
			public const int adjust_width = 2131361793;
			
			// aapt resource value: 0x7f0a0034
			public const int afterGroup = 2131361844;
			
			// aapt resource value: 0x7f0a0036
			public const int afterNo = 2131361846;
			
			// aapt resource value: 0x7f0a0035
			public const int afterYes = 2131361845;
			
			// aapt resource value: 0x7f0a0006
			public const int auto = 2131361798;
			
			// aapt resource value: 0x7f0a000e
			public const int button1 = 2131361806;
			
			// aapt resource value: 0x7f0a0016
			public const int cameraView = 2131361814;
			
			// aapt resource value: 0x7f0a0021
			public const int checkEmail = 2131361825;
			
			// aapt resource value: 0x7f0a0020
			public const int checkPhone = 2131361824;
			
			// aapt resource value: 0x7f0a0022
			public const int checkShadow = 2131361826;
			
			// aapt resource value: 0x7f0a0023
			public const int checkTour = 2131361827;
			
			// aapt resource value: 0x7f0a0024
			public const int checkVisit = 2131361828;
			
			// aapt resource value: 0x7f0a0038
			public const int commentsBox = 2131361848;
			
			// aapt resource value: 0x7f0a0007
			public const int dark = 2131361799;
			
			// aapt resource value: 0x7f0a000d
			public const int editText1 = 2131361805;
			
			// aapt resource value: 0x7f0a001c
			public const int email = 2131361820;
			
			// aapt resource value: 0x7f0a0037
			public const int eventRating = 2131361847;
			
			// aapt resource value: 0x7f0a0011
			public const int eventsButton = 2131361809;
			
			// aapt resource value: 0x7f0a001a
			public const int firstName = 2131361818;
			
			// aapt resource value: 0x7f0a002e
			public const int fulldayGroup = 2131361838;
			
			// aapt resource value: 0x7f0a0030
			public const int fulldayNo = 2131361840;
			
			// aapt resource value: 0x7f0a002f
			public const int fulldayYes = 2131361839;
			
			// aapt resource value: 0x7f0a0027
			public const int goalsAAS = 2131361831;
			
			// aapt resource value: 0x7f0a0028
			public const int goalsBA = 2131361832;
			
			// aapt resource value: 0x7f0a002a
			public const int goalsDont = 2131361834;
			
			// aapt resource value: 0x7f0a0026
			public const int goalsMilitary = 2131361830;
			
			// aapt resource value: 0x7f0a0029
			public const int goalsNoPlan = 2131361833;
			
			// aapt resource value: 0x7f0a0031
			public const int halfdayGroup = 2131361841;
			
			// aapt resource value: 0x7f0a0033
			public const int halfdayNo = 2131361843;
			
			// aapt resource value: 0x7f0a0032
			public const int halfdayYes = 2131361842;
			
			// aapt resource value: 0x7f0a0003
			public const int icon_only = 2131361795;
			
			// aapt resource value: 0x7f0a0009
			public const int imageView1 = 2131361801;
			
			// aapt resource value: 0x7f0a002b
			public const int interestGroup = 2131361835;
			
			// aapt resource value: 0x7f0a002d
			public const int interestNo = 2131361837;
			
			// aapt resource value: 0x7f0a002c
			public const int interestYes = 2131361836;
			
			// aapt resource value: 0x7f0a001b
			public const int lastName = 2131361819;
			
			// aapt resource value: 0x7f0a0008
			public const int light = 2131361800;
			
			// aapt resource value: 0x7f0a0018
			public const int linearLayout1 = 2131361816;
			
			// aapt resource value: 0x7f0a0010
			public const int mapButton = 2131361808;
			
			// aapt resource value: 0x7f0a0002
			public const int none = 2131361794;
			
			// aapt resource value: 0x7f0a001d
			public const int phoneNo = 2131361821;
			
			// aapt resource value: 0x7f0a001f
			public const int programInterest = 2131361823;
			
			// aapt resource value: 0x7f0a0013
			public const int programsButton = 2131361811;
			
			// aapt resource value: 0x7f0a0012
			public const int qrButton = 2131361810;
			
			// aapt resource value: 0x7f0a001e
			public const int ratingBar1 = 2131361822;
			
			// aapt resource value: 0x7f0a0014
			public const int scanHistoryButton = 2131361812;
			
			// aapt resource value: 0x7f0a0019
			public const int schoolSpinner = 2131361817;
			
			// aapt resource value: 0x7f0a0004
			public const int standard = 2131361796;
			
			// aapt resource value: 0x7f0a0015
			public const int surveyButton = 2131361813;
			
			// aapt resource value: 0x7f0a0039
			public const int surveySubmit = 2131361849;
			
			// aapt resource value: 0x7f0a000a
			public const int tableRow1 = 2131361802;
			
			// aapt resource value: 0x7f0a000b
			public const int textView1 = 2131361803;
			
			// aapt resource value: 0x7f0a000c
			public const int textView2 = 2131361804;
			
			// aapt resource value: 0x7f0a000f
			public const int textView3 = 2131361807;
			
			// aapt resource value: 0x7f0a0017
			public const int txtResult = 2131361815;
			
			// aapt resource value: 0x7f0a0005
			public const int wide = 2131361797;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Integer
		{
			
			// aapt resource value: 0x7f070000
			public const int google_play_services_version = 2131165184;
			
			static Integer()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Integer()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f040000
			public const int Events = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int login = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int Main = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int Map = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int Programs = 2130968580;
			
			// aapt resource value: 0x7f040005
			public const int QRScanner = 2130968581;
			
			// aapt resource value: 0x7f040006
			public const int Registration = 2130968582;
			
			// aapt resource value: 0x7f040007
			public const int ScanHistory = 2130968583;
			
			// aapt resource value: 0x7f040008
			public const int ScanInfo = 2130968584;
			
			// aapt resource value: 0x7f040009
			public const int Survey = 2130968585;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7f030000
			public const int Icon = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Iconold = 2130903041;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f060012
			public const int ApplicationName = 2131099666;
			
			// aapt resource value: 0x7f060011
			public const int Hello = 2131099665;
			
			// aapt resource value: 0x7f060013
			public const int app_name = 2131099667;
			
			// aapt resource value: 0x7f060000
			public const int common_google_play_services_enable_button = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int common_google_play_services_enable_text = 2131099649;
			
			// aapt resource value: 0x7f060002
			public const int common_google_play_services_enable_title = 2131099650;
			
			// aapt resource value: 0x7f060003
			public const int common_google_play_services_install_button = 2131099651;
			
			// aapt resource value: 0x7f060004
			public const int common_google_play_services_install_text = 2131099652;
			
			// aapt resource value: 0x7f060005
			public const int common_google_play_services_install_title = 2131099653;
			
			// aapt resource value: 0x7f060006
			public const int common_google_play_services_notification_ticker = 2131099654;
			
			// aapt resource value: 0x7f060010
			public const int common_google_play_services_unknown_issue = 2131099664;
			
			// aapt resource value: 0x7f060007
			public const int common_google_play_services_unsupported_text = 2131099655;
			
			// aapt resource value: 0x7f060008
			public const int common_google_play_services_update_button = 2131099656;
			
			// aapt resource value: 0x7f060009
			public const int common_google_play_services_update_text = 2131099657;
			
			// aapt resource value: 0x7f06000a
			public const int common_google_play_services_update_title = 2131099658;
			
			// aapt resource value: 0x7f06000b
			public const int common_google_play_services_updating_text = 2131099659;
			
			// aapt resource value: 0x7f06000c
			public const int common_google_play_services_wear_update_text = 2131099660;
			
			// aapt resource value: 0x7f06000d
			public const int common_open_on_phone = 2131099661;
			
			// aapt resource value: 0x7f06000e
			public const int common_signin_button_text = 2131099662;
			
			// aapt resource value: 0x7f06000f
			public const int common_signin_button_text_long = 2131099663;
			
			// aapt resource value: 0x7f060014
			public const int school_prompt = 2131099668;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f090000
			public const int CustomTheme = 2131296256;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] LoadingImageView = new int[] {
					2130771968,
					2130771969,
					2130771970};
			
			// aapt resource value: 2
			public const int LoadingImageView_circleCrop = 2;
			
			// aapt resource value: 1
			public const int LoadingImageView_imageAspectRatio = 1;
			
			// aapt resource value: 0
			public const int LoadingImageView_imageAspectRatioAdjust = 0;
			
			public static int[] SignInButton = new int[] {
					2130771971,
					2130771972,
					2130771973};
			
			// aapt resource value: 0
			public const int SignInButton_buttonSize = 0;
			
			// aapt resource value: 1
			public const int SignInButton_colorScheme = 1;
			
			// aapt resource value: 2
			public const int SignInButton_scopeUris = 2;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
